name: Publish demo to GH Pages
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  check-latest: true

            - name: Build
              run: |
                  node -v
                  npm -v
                  npm i -g npm
                  npm -v
                  npm install
                  npm run build
                  npm --prefix=demo install
                  npm --prefix=demo run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: demo/dist
